spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.com.egova.quartz.entity
    